### PR TITLE
#4 add simple mock / use only vrep mock

### PR DESCRIPTION
**Pull request by vicnbt**
added simple mock server
image

### CODE REVIEW

**Comment by chaos-adept** [comment]
@vicnbt  meanwhile, the proximity sensor was merged into master should we use another branch? it looks like the changes are related to all arduino mocking not only proximity

**Comment by chaos-adept** [comment]
for information,

it is interesting from the mock point of view functionality of the node js
https://nodejs.org/dist/latest-v8.x/docs/api/repl.html

it might be integrated with the mock functionality to work with the virtual environment (like proximity sensor)
```
  this.repl.inject({
    // Allow limited on/off control access to the
    // Led instance from the REPL.
    on: function() {
      led.on();
    },
    off: function() {
      led.off();
    }
  });
```

```
>> on()  // will turn on the LED
or
>> off() // will turn off the LED
```

**Comment by vicnbt** [comment]
let's discuss it by skype

**Comment by vicnbt** [comment]
we can make it easier without rewriting all the modules

**Comment by chaos-adept** [comment]
@vicnbt 
lets close this task as wont fix the discussion does not make sense in cause if we have decision to implement mock based on v-rep, i will raise another issue to adjust v-rep simulator to the actual mock needs

**Pull request closed without merging**
